#!/bin/bash

# Build script to extract CloudKit container identifier from entitlements
# and generate CloudKitConfig.swift file

set -e

ENTITLEMENTS_FILE="${SRCROOT}/Gowi/Gowi.entitlements"
OUTPUT_DIR="${SRCROOT}/Gowi/Generated"
OUTPUT_FILE="${OUTPUT_DIR}/CloudKitConfig.swift"

# Ensure output directory exists
mkdir -p "${OUTPUT_DIR}"

# Extract CloudKit container identifier from entitlements
CONTAINER_ID=$(/usr/libexec/PlistBuddy -c "Print :com.apple.developer.icloud-container-identifiers:0" "${ENTITLEMENTS_FILE}" 2>/dev/null || echo "")

if [ -z "${CONTAINER_ID}" ]; then
    echo "Error: No CloudKit container identifier found in entitlements"
    exit 1
fi

# Remove "iCloud." prefix to get container name
CONTAINER_NAME=${CONTAINER_ID#iCloud.}

echo "Generating CloudKitConfig.swift with container name: ${CONTAINER_NAME}"

# Generate Swift file
cat > "${OUTPUT_FILE}" << EOF
//
// CloudKitConfig.swift
// Auto-generated by build script - DO NOT EDIT
//
// Generated from: ${ENTITLEMENTS_FILE}
// Container ID: ${CONTAINER_ID}
//

enum CloudKitConfig {
    /// CloudKit container name extracted from entitlements
    static let containerName = "${CONTAINER_NAME}"
}
EOF

echo "Successfully generated ${OUTPUT_FILE}"